language: objective-c
before_install:
  # Download and unzip Sketch.
  - "wget https://www.sketchapp.com/download/sketch.zip"
  - "unzip sketch.zip"
  # Install SketchTool
  - "Sketch.app/Contents/Resources/sketchtool/install.sh"
  # Install Grunt CLI
  - "npm install -g grunt-cli"
  - "npm install"
script:
  - "npm test"