language: objective-c
before_install:
  # Download, unzip and symlink SketchTool
  - "wget http://sketchtool.bohemiancoding.com/sketchtool-latest.zip"
  - "unzip sketchtool-latest.zip"
  # Install SketchTool
  - "cd sketchtool"
  - "./install.sh"
  - "cd .."
  # Install Grunt CLI
  - "npm install -g grunt-cli"
  - "npm install"
script:
  - "npm test"